#ifndef _PARAM_H
#define _PARAM_H

#define USER_DO_LOGIN_CHOICE_LOGIN 1
#define USER_DO_LOGIN_CHOICE_SIGNUP 2
#define USER_DO_LOGIN_CHOICE_LOGIN_AS_ADMINISTRATOR 3
#define USER_DO_LOGIN_CHOICE_QUIT_LOGIN 4

#define MAIN_MENU_CHOICE_SELL_ITEM '1'
#define MAIN_MENU_CHOICE_STATUS_OF_YOUR_ITEM_LISTED_ON_AUCTION '2'
#define MAIN_MENU_CHOICE_SEARCH_ITEM '3'
#define MAIN_MENU_CHOICE_CHECK_STATUS_OF_YOUR_BID '4'
#define MAIN_MENU_CHOICE_CHECK_YOUR_ACCOUNT '5'
#define MAIN_MENU_QUIT 'Q'

#define SELL_CATEGORY_ELECTROICS 1
#define SELL_CATEGORY_BOOKS 2
#define SELL_CATEGORY_HOME 3
#define SELL_CATEGORY_CLOTHING 4
#define SELL_CATEGORY_SPORTING_GOODS 5

#define SELL_CONDITION_NEW 1
#define SELL_CONDITION_LIKE_NEW 2
#define SELL_CONDITION_USED_GOOD 3
#define SELL_CONDITION_USED_ACCEPTABLE 4

#define SEARCH_ITEM_BY_CATEGORY 1
#define SEARCH_ITEM_BY_DESCRIPTION_KEYWORD 2
#define SEARCH_ITEM_BY_SELLER 3
#define SEARCH_ITEM_BY_DATE_POSTED 4
#define SEARCH_ITEM_GO_BACK 5 // true;
#define SEARCH_ITEM_QUIT 6    // false

#define ADMIN_MAIN_MENU_RESET_BALANCE_MONTHLY '0'
#define ADMIN_MAIN_MENU_NUMBER_OF_USERS '1'
#define ADMIN_MAIN_MENU_NUMBER_OF_ITEMS '2'
#define ADMIN_MAIN_MENU_NUMBER_OF_TRADES '3'
#define ADMIN_MAIN_MENU_AVERAGE_TRADES_PER_ITEMS '4'
#define ADMIN_MAIN_MENU_SUM_OF_COMMISSIONS '5'
#define ADMIN_MAIN_MENU_QUIT 'Q'

#endif
